spring:
  data:
    mongodb:
      uri: mongodb+srv://arman_0212:arman_0212@cluster0.8chashc.mongodb.net/?retryWrites=true&w=majority
      database: buildar


#  security:
#    user:
#      name: user
#      password: user